mysql:  
  host: 127.0.0.1
  port: 3306
  database: TikTokLite
  username: root
  password: 123456
minio:
  #minio服务主机ip，需要填具体ip
  host: 127.0.0.1
  port: 9000
  accessKeyID: admin
  secretAccessKey: admin123456
  videobuckets: video
  picbuckets: pic
redis:
  address: 127.0.0.1
  network: tcp
  port: 6379
videofile: /tmp/file/video/
logfile: /tmp/file/log/
picfile: /tmp/file/picture/
level: info
